# Generated by Django 2.2 on 2020-08-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50),
        ),
    ]
